import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="body-font"> {/* Apply CSS class for body styles */}
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem",
          fontFamily: "cursive", // Set font family for header
          fontWeight: "bolder",
          fontSize: "30px",
        }}>
          <p>HEADER</p>
        </header>
        {children}
      </body>
      <footer style={{
        backgroundColor: "gray",
        padding:"1rem",
        fontFamily:"cursive",
        fontWeight:"bolder",
        fontSize:"30px",
      }}>
        <p>FOOTER</p>
        </footer>
    </html>
  );
}
